# Generated by Django 4.2.1 on 2023-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='judge',
            new_name='judge_language_id',
        ),
        migrations.AddField(
            model_name='language',
            name='compiler_option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
